[tool.poetry]
name = "filestreambot"
version = "0.1.0"
description = ""
authors = ["Divkix <23524935+Divkix@users.noreply.github.com>"]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
Pyrogram = "^1.2.9"
aiohttp = "^3.7.4"
TgCrypto = "^1.2.2"
aiofiles = "^0.7.0"
APScheduler = "^3.7.0"
dnspython = "^2.1.0"
requests = "^2.25.1"
motor = "^2.4.0"
pyromod = {git = "https://github.com/usernein/pyromod"}

[tool.poetry.dev-dependencies]
black = "^21.6b0"
pre-commit = "^2.13.0"
isort = "^5.8.0"
pylint = "^2.8.3"
pyclean = "^2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
