[tool.poetry]
name = "filestreamerbot"
version = "1.0.0"
description = ""
authors = ["Divanshu Chauhan <23524935+Divkix@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Pyrogram = "^2.0.26"
aiohttp = "^3.8.1"
TgCrypto = "^1.2.3"
aiofiles = "^0.8.0"
dnspython = "^2.2.1"
requests = "^2.27.1"
motor = "^3.0.0"
pyshorteners = "^1.0.1"
cachetools = "^5.2.0"
prettyconf = "^2.2.1"
aiohttp-jinja2 = "^1.5"

[tool.poetry.dev-dependencies]
black = "^22.3"
pre-commit = "^2.19.0"
isort = "^5.10.1"
pylint = "^2.13.8"
pyclean = "^2.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
