[tool.poetry]
name = "filestreamerbot"
version = "1.0.0"
description = ""
authors = ["Divanshu Chauhan <23524935+Divkix@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Pyrogram = "^2.0.99"
aiohttp = "^3.8.4"
TgCrypto = "^1.2.5"
aiofiles = "^22.1.0"
dnspython = "^2.3.0"
requests = "^2.28.2"
motor = "^3.1.1"
pyshorteners = "^1.0.1"
cachetools = "^5.3.0"
prettyconf = "^2.2.1"
aiohttp-jinja2 = "^1.5"

[tool.poetry.dev-dependencies]
black = "^22.12.0"
pre-commit = "^3.0.4"
isort = "^5.12.0"
pylint = "^2.16.1"
pyclean = "^2.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
