[tool.poetry]
name = "filestreamerbot"
version = "1.0.0"
description = ""
authors = ["Divanshu Chauhan <23524935+Divkix@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Pyrogram = "~=1.2.9"
aiohttp = "~=3.8.1"
TgCrypto = "~=1.2.2"
aiofiles = "~=0.7.0"
APScheduler = "~=3.8.1"
dnspython = "~=2.1.0"
requests = "~=2.26.0"
motor = "~=2.5.1"
pyshorteners = "~=1.0.1"
cachetools = "^4.2.4"
prettyconf = "^2.2.1"

[tool.poetry.dev-dependencies]
black = "~=21.11b1"
pre-commit = "~=2.15.0"
isort = "~=5.10.1"
pylint = "~=2.11.1"
pyclean = "~=2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
