[tool.poetry]
name = "filestreamerbot"
version = "1.0.0"
description = ""
authors = ["Divanshu Chauhan <23524935+Divkix@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Pyrogram = "^1.3.6"
aiohttp = "^3.8.1"
TgCrypto = "^1.2.3"
aiofiles = "^0.8.0"
APScheduler = "^3.8.1"
dnspython = "^2.2.0"
requests = "^2.27.1"
motor = "^2.5.1"
pyshorteners = "^1.0.1"
cachetools = "^5.0.0"
prettyconf = "^2.2.1"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pre-commit = "^2.17.0"
isort = "^5.10.1"
pylint = "^2.12.2"
pyclean = "^2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
