name: Cloudflare Workers CI
on:
  push:
    paths:
      - 'cf-worker/**'
      - '.github/**'
    branches:
     - main
  pull_request:

defaults:
   run:
     working-directory: cf-worker

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --frozen-lockfile
      - run: npm run lint

  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: ci
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - run: npm install --frozen-lockfile
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: 'cf-worker'
