name: CI
on:
  push:
    branches:
     - main
  pull_request:

jobs:
  ci-cf-worker:
    defaults:
      run:
        working-directory: cf-worker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --frozen-lockfile
      - run: npm run lint

  deploy-cf-worker:
    if: github.event_name != 'pull_request'
    defaults:
      run:
        working-directory: cf-worker
    runs-on: ubuntu-latest
    needs: ci-cf-worker
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - run: npm install --frozen-lockfile
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: 'cf-worker'

  pre-commit:
    uses: divkix/reusable-workflows/.github/workflows/pre-commit.yml@main

  automerge-dependabot-pr:
    needs: pre-commit
    uses: divkix/reusable-workflows/.github/workflows/automerge-dependabot-pr.yml@main

  heroku-push:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
