name: Export requirements.txt
on:
  workflow_dispatch:
  push:
jobs:
  export-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Poetry export requirements.txt
        uses: DivideProjects/poetry-export-requirements-txt@v1
      - run: |
          cat requirements.txt
